name: CI Mon Projet Angular

env:
  NODE_VERSION: '22'

on:
  push:
    branches: [ "main"]


jobs:
  build:


    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo بِسْمِ ٱللَّٰهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ
      
      - name:  Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Install dependencies
        working-directory: snifly        
        run: npm install

      - name: Build Angular application
        working-directory: snifly
        run: npm run build
  test :
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Install dependencies
        working-directory: snifly        
        run: npm install

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Déploiement
        run: echo "Salam 3laiakom Siiiir Deplyer fi serveur "

      - uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Install dependencies
        working-directory: snifly        
        run: npm install

      - name: Build Angular application
        working-directory: snifly
        run: npm run build

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'demoangular'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: './snifly/dist'
